const mongoose = require("mongoose");
const dotenv = require("dotenv");
const path = require("path");

dotenv.config({ path: path.join(__dirname, "../.env") });

const Event = require("../models/Event");

const verifiedEvents = [
  {
    title: "Smart India Hackathon (SIH) 2026",
    type: "Hackathon",
    organizer: "AICTE & Ministry of Education, Govt. of India",
    description: "India's premier nationwide innovation hackathon bringing together college students to solve pressing problem statements proposed by central ministries, state departments, and top industries.",
    location: "New Delhi & Nodal Centers Nationwide",
    mode: "Hybrid",
    registrationUrl: "https://www.sih.gov.in",
    registrationLink: "https://www.sih.gov.in",
    officialSourceUrl: "https://www.sih.gov.in",
    officialSourceName: "AICTE & MoE Official Portal",
    isOfficialVerified: true,
    eventDate: new Date("2026-09-22T09:00:00Z"),
    eventEndDate: new Date("2026-09-24T18:00:00Z"),
    registrationDeadline: new Date("2026-08-30T23:59:59Z"),
    deadline: new Date("2026-08-30T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["Web Development", "AI/ML", "Cloud", "Mobile", "IoT", "Problem Solving"],
    eligibility: "Regular undergraduate and postgraduate students from recognized Indian colleges.",
    featured: true,
  },
  {
    title: "Microsoft Imagine Cup 2026 Global Student Competition",
    type: "Hackathon",
    organizer: "Microsoft",
    description: "The global student technology challenge empowering founders and developers to build purpose-driven AI and cloud technology startups using Azure and OpenAI models.",
    location: "Global / Online",
    mode: "Online",
    registrationUrl: "https://imaginecup.microsoft.com",
    registrationLink: "https://imaginecup.microsoft.com",
    officialSourceUrl: "https://imaginecup.microsoft.com",
    officialSourceName: "Microsoft Student Developer Hub",
    isOfficialVerified: true,
    eventDate: new Date("2026-10-15T10:00:00Z"),
    registrationDeadline: new Date("2026-08-16T23:59:59Z"),
    deadline: new Date("2026-08-16T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "UTC / Global",
    skills: ["AI/ML", "Cloud", "Web Development", "Mobile", "General Software Development"],
    eligibility: "Students aged 16+ enrolled in accredited educational institutions worldwide.",
    featured: true,
  },
  {
    title: "ICPC Asia Regional Preliminary Contest",
    type: "Coding Contest",
    organizer: "International Collegiate Programming Contest (ICPC Foundation)",
    description: "The oldest and most prestigious competitive programming championship for university students, testing algorithmic mastery, data structures, and high-pressure team problem solving.",
    location: "Online / Regional Sites",
    mode: "Online",
    registrationUrl: "https://icpc.global",
    registrationLink: "https://icpc.global",
    officialSourceUrl: "https://icpc.global/regionals/finder",
    officialSourceName: "ICPC Global Foundation",
    isOfficialVerified: true,
    eventDate: new Date("2026-09-06T14:00:00Z"),
    registrationDeadline: new Date("2026-08-15T23:59:59Z"),
    deadline: new Date("2026-08-15T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["DSA", "General Software Development", "Algorithms", "Problem Solving"],
    eligibility: "Teams of 3 eligible university students registered through official university coach.",
    featured: true,
  },
  {
    title: "AWS Innovate: AI & Cloud Online Conference",
    type: "Conference",
    organizer: "Amazon Web Services (AWS)",
    description: "Official AWS technical conference dedicated to developers, engineers, and students looking to architect, deploy, and scale machine learning and cloud architectures on AWS.",
    location: "Online (Asia-Pacific / Global)",
    mode: "Online",
    registrationUrl: "https://aws.amazon.com/events/aws-innovate/",
    registrationLink: "https://aws.amazon.com/events/aws-innovate/",
    officialSourceUrl: "https://aws.amazon.com/events/aws-innovate/",
    officialSourceName: "Amazon Web Services Official Events",
    isOfficialVerified: true,
    eventDate: new Date("2026-08-27T09:00:00Z"),
    registrationDeadline: new Date("2026-08-26T23:59:59Z"),
    deadline: new Date("2026-08-26T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["Cloud", "AI/ML", "DevOps", "Data Science"],
    eligibility: "Open to all developers, students, and cloud enthusiasts worldwide.",
    featured: false,
  },
  {
    title: "Google Solution Challenge – Global Community Showcase",
    type: "Hackathon",
    organizer: "Google Developer Groups & Google for Developers",
    description: "Global student initiative challenging university teams to develop real-world software solutions addressing the United Nations 17 Sustainable Development Goals using Google tools.",
    location: "Online",
    mode: "Online",
    registrationUrl: "https://developers.google.com/community/gdsc-solution-challenge",
    registrationLink: "https://developers.google.com/community/gdsc-solution-challenge",
    officialSourceUrl: "https://developers.google.com/community/gdsc-solution-challenge",
    officialSourceName: "Google for Developers",
    isOfficialVerified: true,
    eventDate: new Date("2026-11-10T14:00:00Z"),
    registrationDeadline: new Date("2026-09-15T23:59:59Z"),
    deadline: new Date("2026-09-15T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "Global (UTC)",
    skills: ["Web Development", "Cloud", "AI/ML", "Mobile", "DevOps"],
    eligibility: "University students worldwide.",
    featured: false,
  },
  {
    title: "NVIDIA DLI: Fundamentals of Deep Learning Workshop",
    type: "Workshop",
    organizer: "NVIDIA Deep Learning Institute",
    description: "Hands-on instructor-led technical workshop exploring deep neural networks, computer vision classification, data augmentation, and GPU-accelerated model training on NVIDIA hardware.",
    location: "Online",
    mode: "Online",
    registrationUrl: "https://www.nvidia.com/en-us/training/",
    registrationLink: "https://www.nvidia.com/en-us/training/",
    officialSourceUrl: "https://www.nvidia.com/en-us/training/",
    officialSourceName: "NVIDIA Deep Learning Institute",
    isOfficialVerified: true,
    eventDate: new Date("2026-09-18T10:00:00Z"),
    registrationDeadline: new Date("2026-09-10T23:59:59Z"),
    deadline: new Date("2026-09-10T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["AI/ML", "Data Science", "Python"],
    eligibility: "Engineers, computer science students, and researchers with basic Python knowledge.",
    featured: false,
  },
  {
    title: "PyCon India 2026 Technical Conference",
    type: "Conference",
    organizer: "Python Software Society of India",
    description: "The largest annual volunteer-driven conference for the Python programming language in India, featuring technical deep-dives on backend architectures, data engineering, and AI pipelines.",
    location: "Bengaluru, Karnataka & Online",
    mode: "Hybrid",
    registrationUrl: "https://in.pycon.org",
    registrationLink: "https://in.pycon.org",
    officialSourceUrl: "https://in.pycon.org",
    officialSourceName: "Python Software Society of India",
    isOfficialVerified: true,
    eventDate: new Date("2026-09-26T09:00:00Z"),
    registrationDeadline: new Date("2026-09-15T23:59:59Z"),
    deadline: new Date("2026-09-15T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["Web Development", "Data Science", "AI/ML", "DevOps", "General Software Development"],
    eligibility: "Open to all students, researchers, and professional software developers.",
    featured: false,
  },
  {
    title: "Google Summer of Code (GSoC) Midterm Developer Forum",
    type: "Webinar",
    organizer: "Google Open Source",
    description: "Interactive session and live project showcases by student developers and open source mentors discussing large-scale repository contributions and distributed engineering workflows.",
    location: "Online",
    mode: "Online",
    registrationUrl: "https://summerofcode.withgoogle.com",
    registrationLink: "https://summerofcode.withgoogle.com",
    officialSourceUrl: "https://summerofcode.withgoogle.com",
    officialSourceName: "Google Open Source Programs Office",
    isOfficialVerified: true,
    eventDate: new Date("2026-08-20T16:00:00Z"),
    registrationDeadline: new Date("2026-08-14T23:59:59Z"),
    deadline: new Date("2026-08-14T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "Global (UTC)",
    skills: ["General Software Development", "Web Development", "DevOps", "DSA"],
    eligibility: "Open to all global student developers.",
    featured: false,
  },
  {
    title: "AWS Summit Bengaluru 2026",
    type: "Tech Event",
    organizer: "Amazon Web Services (AWS)",
    description: "Concluded regional flagship cloud summit featuring executive keynotes, infrastructure tracks, and cloud architectural best practices. Session recordings, slides, and whitepapers are archived on the official summit portal.",
    location: "BIEC Bengaluru, Karnataka",
    mode: "Offline",
    registrationUrl: "https://aws.amazon.com/events/summits/bengaluru/",
    registrationLink: "https://aws.amazon.com/events/summits/bengaluru/",
    officialSourceUrl: "https://aws.amazon.com/events/summits/bengaluru/",
    officialSourceName: "AWS Summit Official Archives",
    isOfficialVerified: true,
    eventDate: new Date("2026-04-22T08:30:00Z"),
    eventEndDate: new Date("2026-04-23T18:00:00Z"),
    registrationDeadline: new Date("2026-04-20T23:59:59Z"),
    deadline: new Date("2026-04-20T23:59:59Z"),
    deadlineUnknown: false,
    timezone: "IST (UTC+5:30)",
    skills: ["Cloud", "DevOps", "Cybersecurity", "AI/ML", "Data Science"],
    eligibility: "Concluded event - archives available.",
    pastResourcesUrl: "https://aws.amazon.com/events/summits/bengaluru/",
    featured: false,
  }
];

const seedEvents = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI || "mongodb://127.0.0.1:27017/career_navigation_platform";
    console.log("Connecting to MongoDB Atlas...");
    await mongoose.connect(mongoUri, { serverSelectionTimeoutMS: 10000 });

    console.log("Cleaning old event records...");
    await Event.deleteMany({});

    console.log(`Inserting ${verifiedEvents.length} verified events...`);
    const inserted = await Event.insertMany(verifiedEvents);

    console.log(`✅ Successfully seeded ${inserted.length} verified events from official organizers.`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Failed to seed events:", error);
    process.exit(1);
  }
};

seedEvents();
