require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const Scholarship = require("../models/Scholarship");

// Verified active scholarships dataset (Zero closed entries)
const verifiedScholarships = [
  // ==========================================
  // 1. BUDDY4STUDY PORTAL SCHOLARSHIPS
  // ==========================================
  {
    title: "HDFC Bank Parivartan's ECSS Programme",
    provider: "HDFC Bank Foundation",
    description:
      "A flagship initiative by HDFC Bank providing financial assistance to meritorious students facing personal or family crises to ensure unhindered continuation of diploma, undergraduate, and postgraduate education.",
    awardAmount: "Up to ₹75,000 / year",
    awardAmountValue: 75000,
    currency: "INR",
    category: "Corporate",
    type: "Need-based",
    eligibilitySummary: "Undergraduate, postgraduate, and diploma students who have passed their previous qualifying examination with at least 55% marks and whose family annual income is <= ₹2.5 Lakhs or facing family crisis.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate", "Diploma", "12th"],
    minimumPercentage: 55,
    minimumCGPA: 5.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "BCA", "MCA", "B.Sc", "M.Tech", "All"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹2,50,000",
    maxAnnualIncome: 250000,
    genderRequirement: "All",
    benefits: [
      "Financial assistance of up to ₹75,000 per annum towards tuition and institutional fees",
      "Protection from academic discontinuation during economic distress",
    ],
    requiredDocuments: [
      "Previous year academic marksheet (minimum 55% marks)",
      "Current year admission proof (College ID Card / Fee Receipt / Bonafide)",
      "Income proof (Income Certificate / Salary Slip / ITR / Gram Panchayat proof)",
      "Crisis proof (if applicable: medical bills, demise certificate of earning member)",
      "Government photo ID (Aadhaar Card) & Bank Account Details",
    ],
    applicationOpenDate: new Date("2026-06-01"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "October 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Registration on Buddy4Study",
        description: "Log in with registered email or mobile number on Buddy4Study portal.",
      },
      {
        stepNumber: 2,
        title: "Application Form Filling",
        description: "Fill the online application form for HDFC Bank Parivartan ECSS Programme.",
      },
      {
        stepNumber: 3,
        title: "Document Upload & Verification",
        description: "Upload marks cards, income proofs, and bank details.",
      },
      {
        stepNumber: 4,
        title: "Screening & Direct Bank Transfer",
        description: "Telephonic verification followed by direct scholarship disbursement to student's bank account.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-programme",
    officialSourceUrl: "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-programme",
    sourceUrl: "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-programme",
    officialSourceName: "Buddy4Study / HDFC Bank Parivartan",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computing", "Applied Sciences", "Problem Solving"],
    careerPaths: ["Software Engineer", "Full Stack Developer", "Data Analyst", "Civil Engineer"],
    isActive: true,
  },
  {
    title: "Kotak Kanya Scholarship",
    provider: "Kotak Education Foundation",
    description:
      "A flagship CSR scholarship program for meritorious girl students from underprivileged backgrounds who have secured admission to 1st year of professional graduation degree programs at recognized institutes in India.",
    awardAmount: "₹1,50,000 / year",
    awardAmountValue: 150000,
    currency: "INR",
    category: "Corporate",
    type: "Women",
    eligibilitySummary: "Meritorious girl students admitted to 1st year of professional undergraduate degree programs (Engineering, MBBS, Architecture, Design, LLB) who scored >= 85% in Class 12 board examination with annual family income <= ₹6 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 85,
    minimumCGPA: 8.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "MBBS", "B.Arch", "LLB"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Electrical", "Mechanical", "Civil"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["India", "Karnataka", "Maharashtra", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹6,00,000",
    maxAnnualIncome: 600000,
    genderRequirement: "Female",
    benefits: [
      "Scholarship grant of ₹1,50,000 per year until the completion of the professional degree",
      "Mentorship, career readiness training, and holistic empowerment from Kotak Education Foundation",
    ],
    requiredDocuments: [
      "Class 12 board marksheet (minimum 85% marks)",
      "Entrance exam scorecard (JEE / CET / State Entrance)",
      "College admission letter and fee receipt",
      "Family income certificate / ITR",
      "Aadhaar card & Student bank passbook",
    ],
    applicationOpenDate: new Date("2026-06-15"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Buddy4Study Application",
        description: "Submit online application with academic and family income documentation on Buddy4Study.",
      },
      {
        stepNumber: 2,
        title: "Document Screening",
        description: "Review of Class 12 marks, rank card, and financial eligibility.",
      },
      {
        stepNumber: 3,
        title: "Interview Rounds",
        description: "Virtual interview with Kotak Education Foundation selection panel.",
      },
      {
        stepNumber: 4,
        title: "Scholarship Award & Mentorship Induction",
        description: "Annual fund sanction and onboarding into the Kotak Kanya Scholar community.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/kotak-kanya-scholarship",
    officialSourceUrl: "https://www.buddy4study.com/page/kotak-kanya-scholarship",
    sourceUrl: "https://www.buddy4study.com/page/kotak-kanya-scholarship",
    officialSourceName: "Buddy4Study / Kotak Education Foundation",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Leadership", "Computing", "Applied Sciences"],
    careerPaths: ["Software Engineer", "Systems Architect", "Data Scientist", "Core Engineering"],
    isActive: true,
  },
  {
    title: "Infosys Foundation STEM Stars Scholarship",
    provider: "Infosys Foundation",
    description:
      "Supporting first-year female students in India pursuing undergraduate degrees in Science, Technology, Engineering, and Mathematics (STEM) at premier NIRF-accredited institutions.",
    awardAmount: "₹1,00,000 / year",
    awardAmountValue: 100000,
    currency: "INR",
    category: "STEM/Engineering",
    type: "Women",
    eligibilitySummary: "Female students enrolled in 1st year of undergraduate STEM degrees (Engineering, Computing, Applied Sciences) with min. 7.0 CGPA / 60% in Class 12 and annual household income <= ₹8 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 7.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "B.Tech", "B.E.", "B.Sc STEM"],
    eligibleBranches: ["Computer Science", "Information Technology", "Artificial Intelligence", "Electronics & Communication", "Electrical", "Mechanical"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹8,00,000",
    maxAnnualIncome: 800000,
    genderRequirement: "Female",
    benefits: [
      "Financial assistance of up to ₹1,00,000 annually covering tuition fees, books, and living expenses",
      "Access to Infosys Foundation mentorship and technical community networks",
    ],
    requiredDocuments: [
      "Class 12 marksheet and Class 10 certificate",
      "NIRF ranked institute college admission letter and fee breakdown",
      "Income certificate issued by competent authority",
      "Aadhaar card & Student bank account details",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-09-15T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Buddy4Study Registration & Profile",
        description: "Complete student profile and apply under Infosys Foundation STEM Stars.",
      },
      {
        stepNumber: 2,
        title: "Academic & Institutional Verification",
        description: "Verification of college enrollment and NIRF ranking tier.",
      },
      {
        stepNumber: 3,
        title: "Document Review & Merit Shortlisting",
        description: "Committee evaluates academic merit and financial background.",
      },
      {
        stepNumber: 4,
        title: "Scholarship Disbursement",
        description: "Annual grant credited directly via DBT.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/infosys-foundation-stem-stars-scholarship",
    officialSourceUrl: "https://www.buddy4study.com/page/infosys-foundation-stem-stars-scholarship",
    sourceUrl: "https://www.buddy4study.com/page/infosys-foundation-stem-stars-scholarship",
    officialSourceName: "Buddy4Study / Infosys Foundation",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Software Engineering", "Algorithms", "Cloud Computing", "AI/ML"],
    careerPaths: ["Software Engineer", "AI/ML Engineer", "Cloud Architect", "Full Stack Developer"],
    isActive: true,
  },
  {
    title: "The Tata Capital Pankh Scholarship Programme",
    provider: "Tata Capital Limited",
    description:
      "A flagship CSR initiative by Tata Capital Limited hosted on Buddy4Study to empower deserving students from economically weaker sections to pursue undergraduate degree and diploma studies by covering up to 80% of course fees.",
    awardAmount: "Up to ₹1,00,000 (Up to 80% of Tuition Fees)",
    awardAmountValue: 100000,
    currency: "INR",
    category: "Corporate",
    type: "Need-based",
    eligibilitySummary: "Students pursuing Diploma, Polytechnic, or Undergraduate degree programs (B.Tech, B.E., BCA, B.Sc, B.Com, BBA) who scored >= 60% in previous exam with family income <= ₹2.5 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Diploma", "12th"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "BCA", "B.Sc", "BBA", "B.Com", "Diploma"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "Maharashtra", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹2,50,000",
    maxAnnualIncome: 250000,
    genderRequirement: "All",
    benefits: [
      "Up to 80% of tuition and academic fees (capped up to ₹1,00,000 for undergraduate and ₹12,000 for school/diploma)",
      "Skill development workshops and career orientation programs",
    ],
    requiredDocuments: [
      "Previous academic year marksheet (min 60% marks)",
      "Government photo ID card (Aadhaar Card / Voter ID)",
      "Current year college fee receipt and admission bonafide",
      "Income proof issued by Tehsildar / Competent Government authority",
      "Student bank account passbook / cancelled cheque",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-09-30T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Portal Registration",
        description: "Submit online application through Buddy4Study with required personal and fee details.",
      },
      {
        stepNumber: 2,
        title: "Document Verification",
        description: "Screening of academic transcripts and family income documents.",
      },
      {
        stepNumber: 3,
        title: "Telephonic Interaction",
        description: "Brief background verification call with student and parents.",
      },
      {
        stepNumber: 4,
        title: "Direct Fund Credit",
        description: "Scholarship grant credited to student's verified bank account.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/the-tata-capital-pankh-scholarship-programme",
    officialSourceUrl: "https://www.tatacapital.com",
    sourceUrl: "https://www.buddy4study.com/page/the-tata-capital-pankh-scholarship-programme",
    officialSourceName: "Buddy4Study / Tata Capital Limited",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Problem Solving", "Engineering", "Computing", "Technical Literacy"],
    careerPaths: ["Software Engineer", "Systems Analyst", "Network Engineer", "Core Engineering"],
    isActive: true,
  },
  {
    title: "Schaeffler India Hope Engineering Scholarship",
    provider: "Schaeffler India",
    description:
      "Schaeffler India's CSR scholarship dedicated to funding talented engineering students from underprivileged backgrounds across Maharashtra, Gujarat, and Tamil Nadu to complete their 4-year engineering degrees.",
    awardAmount: "Up to ₹75,000 / year",
    awardAmountValue: 75000,
    currency: "INR",
    category: "Corporate",
    type: "Merit-cum-Means",
    eligibilitySummary: "1st year engineering students (B.E./B.Tech) in Gujarat, Maharashtra, or Tamil Nadu with min. 60% in Class 12 (Science) and family income <= ₹5 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Mechanical", "Electronics", "Computer Science", "Information Technology", "B.Tech", "B.E."],
    eligibleBranches: ["Mechanical", "Production", "Mechatronics", "Automobile", "Electrical", "Electronics", "Computer Science"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["Maharashtra", "Gujarat", "Tamil Nadu", "India"],
    eligibleStates: ["Maharashtra", "Gujarat", "Tamil Nadu"],
    incomeRequirement: "Annual family income <= ₹5,00,000",
    maxAnnualIncome: 500000,
    genderRequirement: "All",
    benefits: [
      "Up to ₹75,000 per year towards tuition, books, and examination fees",
      "Mentorship and technical internship consideration with Schaeffler India",
    ],
    requiredDocuments: [
      "Class 10 and Class 12 passing certificates & marksheets",
      "College admission letter & fee receipt",
      "Government issued Income Certificate",
      "Aadhaar card & Bank details",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-08-14T23:59:59.000Z"), // Closing Soon
    deadlineUnknown: false,
    resultDate: "September 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Buddy4Study Application",
        description: "Submit online application on Buddy4Study with engineering admission details.",
      },
      {
        stepNumber: 2,
        title: "Document Verification",
        description: "Validation of income certificates and state residence credentials.",
      },
      {
        stepNumber: 3,
        title: "Personal Interview",
        description: "Online interaction with Schaeffler India CSR team.",
      },
      {
        stepNumber: 4,
        title: "Scholarship Grant",
        description: "Award letter issued and annual fee subsidy transferred.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/schaeffler-india-hope-engineering-scholarship",
    officialSourceUrl: "https://www.buddy4study.com/page/schaeffler-india-hope-engineering-scholarship",
    sourceUrl: "https://www.buddy4study.com/page/schaeffler-india-hope-engineering-scholarship",
    officialSourceName: "Buddy4Study / Schaeffler India",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Mechanical Engineering", "Mechatronics", "Automation", "Applied Physics"],
    careerPaths: ["Mechanical Engineer", "Automation Engineer", "Core Engineering", "Design Engineer"],
    isActive: true,
  },
  {
    title: "Rolls-Royce Unnati Scholarship for Women Engineering Students",
    provider: "Rolls-Royce India",
    description:
      "A flagship diversity and inclusion initiative by Rolls-Royce India supporting female undergraduate engineering students in aerospace, mechanical, electrical, and computer engineering disciplines.",
    awardAmount: "₹35,000 / year",
    awardAmountValue: 35000,
    currency: "INR",
    category: "STEM/Engineering",
    type: "Women",
    eligibilitySummary: "Female students currently in 1st, 2nd, or 3rd year of B.Tech/B.E. engineering programs with at least 60% in Class 10 and Class 12 board examinations in AICTE-recognized colleges.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E."],
    eligibleBranches: ["Mechanical", "Electronics", "Electrical", "Computer Science", "Information Technology", "Aerospace"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "",
    maxAnnualIncome: 0,
    genderRequirement: "Female",
    benefits: [
      "Annual financial grant of ₹35,000 towards academic and lab fees",
      "Opportunity for technical webinar sessions with Rolls-Royce engineers",
    ],
    requiredDocuments: [
      "Class 10 and 12 marksheets",
      "College ID card and current semester bonafide certificate",
      "Aadhaar card copy",
      "Bank account details",
    ],
    applicationOpenDate: new Date("2026-07-10"),
    applicationDeadline: new Date("2026-08-16T23:59:59.000Z"), // Closing Soon
    deadlineUnknown: false,
    resultDate: "September 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Buddy4Study Application",
        description: "Submit online application on Buddy4Study with engineering mark cards.",
      },
      {
        stepNumber: 2,
        title: "Merit Evaluation",
        description: "Evaluation based on academic record and branch of engineering study.",
      },
      {
        stepNumber: 3,
        title: "Award Disbursement",
        description: "Direct bank transfer of scholarship funds to selected female engineering scholars.",
      },
    ],
    applicationUrl: "https://www.buddy4study.com/page/rolls-royce-unnati-scholarships-for-women-engineering-students",
    officialSourceUrl: "https://www.buddy4study.com/page/rolls-royce-unnati-scholarships-for-women-engineering-students",
    sourceUrl: "https://www.buddy4study.com/page/rolls-royce-unnati-scholarships-for-women-engineering-students",
    officialSourceName: "Buddy4Study / Rolls-Royce India",
    sourcePortal: "Buddy4Study",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Mechanical Systems", "Embedded Systems", "Engineering", "Algorithms"],
    careerPaths: ["Hardware Engineer", "Software Engineer", "Embedded Engineer", "Robotics Engineer"],
    isActive: true,
  },

  // ==========================================
  // 2. VIDYASAARATHI PORTAL SCHOLARSHIPS
  // ==========================================
  {
    title: "JSW Udaan Scholarship for B.E./B.Tech Students",
    provider: "JSW Foundation (Vidyasaarathi Portal)",
    description:
      "A flagship CSR scholarship program by JSW Foundation managed on the Vidyasaarathi portal providing financial assistance to deserving undergraduate engineering students across India.",
    awardAmount: "₹50,000 / year",
    awardAmountValue: 50000,
    currency: "INR",
    category: "Corporate",
    type: "Need-based",
    eligibilitySummary: "Full-time B.E./B.Tech engineering students with minimum 60% in Class 10, Class 12, or Diploma and annual family income <= ₹8.0 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E."],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "Electrical", "Metallurgy"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "Maharashtra", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹8,00,000",
    maxAnnualIncome: 800000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of ₹50,000 towards institutional tuition and exam fees",
      "Direct benefit credit through Vidyasaarathi financial disbursement gateway",
    ],
    requiredDocuments: [
      "Class 10, 12, and latest semester engineering marksheets",
      "College admission letter / Bonafide certificate",
      "Current year college fee structure & payment receipt",
      "Income certificate issued by competent government authority",
      "Aadhaar card & Bank passbook copy",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-09-30T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Vidyasaarathi Account Registration",
        description: "Register on www.vidyasaarathi.co.in and complete student profile with academic history.",
      },
      {
        stepNumber: 2,
        title: "Search & Apply Scheme",
        description: "Select 'JSW Udaan Scholarship for B.E./B.Tech' from the scholarship catalogue.",
      },
      {
        stepNumber: 3,
        title: "Document Upload & Verification",
        description: "Upload marks cards, fee receipts, and revenue income certificate for scrutiny.",
      },
      {
        stepNumber: 4,
        title: "Sanction & Credit",
        description: "Direct scholarship disbursement to student bank account upon committee sanction.",
      },
    ],
    applicationUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceUrl: "https://www.vidyasaarathi.co.in",
    sourceUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceName: "Vidyasaarathi Portal / JSW Foundation",
    sourcePortal: "Vidyasaarathi",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computing", "Applied Sciences", "Technical Problem Solving"],
    careerPaths: ["Software Engineer", "Core Engineering", "Data Analyst", "Full Stack Developer"],
    isActive: true,
  },
  {
    title: "Schindler Igniting Minds (SIM) Scholarship for Engineering & Diploma",
    provider: "Schindler India (Vidyasaarathi Portal)",
    description:
      "An initiative by Schindler India on Vidyasaarathi to support meritorious engineering and polytechnic diploma students from rural and economically constrained backgrounds.",
    awardAmount: "Up to ₹75,000 / year",
    awardAmountValue: 75000,
    currency: "INR",
    category: "Corporate",
    type: "Merit-cum-Means",
    eligibilitySummary: "Full-time B.E./B.Tech and Diploma students (Mechanical, Electrical, Electronics, Civil, Computer Science) with min. 65% in Class 10/12 and family income <= ₹3 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Diploma"],
    minimumPercentage: 65,
    minimumCGPA: 6.5,
    eligibleCourses: ["Engineering", "Mechanical", "Electronics", "Electrical", "Civil", "Computer Science", "B.Tech", "B.E.", "Diploma"],
    eligibleBranches: ["Mechanical", "Electrical", "Electronics", "Civil", "Computer Science", "Information Technology"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "Maharashtra", "Tamil Nadu", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹3,00,000",
    maxAnnualIncome: 300000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of up to ₹75,000 for degree and ₹30,000 for diploma courses",
      "Opportunity for Schindler technical apprenticeship and industrial exposure",
    ],
    requiredDocuments: [
      "Class 10, 12, or Diploma marksheets (minimum 65% aggregate)",
      "College admission letter & tuition fee receipt",
      "Competent authority Income Certificate",
      "Aadhaar card copy & Student bank account details",
    ],
    applicationOpenDate: new Date("2026-06-15"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "October 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Vidyasaarathi Application",
        description: "Apply on www.vidyasaarathi.co.in under Schindler Igniting Minds scheme.",
      },
      {
        stepNumber: 2,
        title: "Document Screening",
        description: "Vidyasaarathi desk verification of marksheets and income certificates.",
      },
      {
        stepNumber: 3,
        title: "Schindler CSR Review",
        description: "Evaluation and merit listing by Schindler India review panel.",
      },
      {
        stepNumber: 4,
        title: "Disbursement",
        description: "Fund credit directly to beneficiary bank accounts.",
      },
    ],
    applicationUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceUrl: "https://www.vidyasaarathi.co.in",
    sourceUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceName: "Vidyasaarathi Portal / Schindler India",
    sourcePortal: "Vidyasaarathi",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Mechanical Systems", "Electrical Engineering", "Electronics", "Applied Mathematics"],
    careerPaths: ["Mechanical Engineer", "Electrical Engineer", "Automation Engineer", "Hardware Specialist"],
    isActive: true,
  },
  {
    title: "Lowe's India Scholarship for Engineering Students",
    provider: "Lowe's India (Vidyasaarathi Portal)",
    description:
      "A specialized scholarship program by Lowe's India hosted on Vidyasaarathi to promote technical excellence and support meritorious engineering students in Computer Science, IT, and Circuital branches.",
    awardAmount: "₹60,000 / year",
    awardAmountValue: 60000,
    currency: "INR",
    category: "STEM/Engineering",
    type: "Merit-cum-Means",
    eligibilitySummary: "Full-time B.E./B.Tech students in Computer Science, Information Technology, or Electronics & Communication with min. 60% in Class 10/12 and family income <= ₹5.0 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "B.Tech", "B.E."],
    eligibleBranches: ["Computer Science", "Information Technology", "Electronics & Communication", "Data Science", "Artificial Intelligence"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["Karnataka", "All States"],
    incomeRequirement: "Annual family income <= ₹5,00,000",
    maxAnnualIncome: 500000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of ₹60,000 for college tuition and laboratory fees",
      "Opportunity to participate in Lowe's India tech hackathons and tech talks",
    ],
    requiredDocuments: [
      "Class 10 and 12 marksheets",
      "College admission letter and latest fee receipt",
      "Income certificate from competent authority",
      "Aadhaar card & Bank passbook",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-09-15T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Vidyasaarathi Portal Application",
        description: "Submit online application on Vidyasaarathi under Lowe's India scholarship.",
      },
      {
        stepNumber: 2,
        title: "Academic Screening",
        description: "Verification of semester marks cards and CS/IT stream enrollment.",
      },
      {
        stepNumber: 3,
        title: "Selection & Sanction",
        description: "Final award letter issued and funds disbursed via DBT.",
      },
    ],
    applicationUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceUrl: "https://www.vidyasaarathi.co.in",
    sourceUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceName: "Vidyasaarathi Portal / Lowe's India",
    sourcePortal: "Vidyasaarathi",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Algorithms", "Data Structures", "Java", "Python", "Web Development"],
    careerPaths: ["Software Engineer", "Cloud Engineer", "Backend Developer", "DevOps Engineer"],
    isActive: true,
  },
  {
    title: "ACC Vidyasaarathi Scholarship for Professional Degree & Engineering",
    provider: "ACC Limited / Adani Foundation (Vidyasaarathi Portal)",
    description:
      "A CSR initiative by ACC Limited on the Vidyasaarathi portal supporting students pursuing full-time professional degrees and engineering courses from economically weaker communities.",
    awardAmount: "Up to ₹50,000 / year",
    awardAmountValue: 50000,
    currency: "INR",
    category: "Corporate",
    type: "Need-based",
    eligibilitySummary: "Students pursuing full-time Undergraduate, B.Tech, or Diploma programs with min. 50% in previous exams and family income <= ₹5.0 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Diploma"],
    minimumPercentage: 50,
    minimumCGPA: 5.0,
    eligibleCourses: ["Engineering", "Civil", "Mechanical", "Electrical", "Computer Science", "B.Tech", "B.E.", "Diploma"],
    eligibleBranches: ["All Engineering", "Civil", "Mechanical", "Electrical", "Computer Science", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹5,00,000",
    maxAnnualIncome: 500000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of up to ₹50,000 towards institutional tuition and exam fees",
    ],
    requiredDocuments: [
      "Previous year academic marksheet (min 50% marks)",
      "College fee receipt and admission bonafide",
      "Income certificate from Tahsildar / Revenue officer",
      "Aadhaar card & Student bank passbook",
    ],
    applicationOpenDate: new Date("2026-07-15"),
    applicationDeadline: new Date("2026-10-15T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Registration & Application",
        description: "Submit online application through Vidyasaarathi portal.",
      },
      {
        stepNumber: 2,
        title: "Document Verification",
        description: "Verification of marks and family income proof.",
      },
      {
        stepNumber: 3,
        title: "Fund Sanction",
        description: "Scholarship release directly to beneficiary account.",
      },
    ],
    applicationUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceUrl: "https://www.vidyasaarathi.co.in",
    sourceUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceName: "Vidyasaarathi Portal / ACC Limited",
    sourcePortal: "Vidyasaarathi",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Civil Engineering", "Applied Sciences"],
    careerPaths: ["Civil Engineer", "Core Engineering", "Project Engineer"],
    isActive: true,
  },
  {
    title: "NSDL Shiksha Sahayog Scholarship for Undergraduate & PG Students",
    provider: "NSDL (National Securities Depository Limited)",
    description:
      "A CSR initiative by NSDL on Vidyasaarathi portal providing financial support to meritorious undergraduate and postgraduate students from low-income families.",
    awardAmount: "₹20,000 – ₹30,000 / year",
    awardAmountValue: 30000,
    currency: "INR",
    category: "Corporate",
    type: "Need-based",
    eligibilitySummary: "Undergraduate and postgraduate students pursuing general or professional degree programs with min. 60% in Class 12 or Graduation and family income <= ₹3 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Computer Science", "B.Tech", "B.E.", "BCA", "MCA", "B.Sc", "M.Tech", "Undergraduate", "Postgraduate"],
    eligibleBranches: ["All Branches", "Computer Science", "Information Technology", "Commerce & Science"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "Karnataka", "Maharashtra", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹3,00,000",
    maxAnnualIncome: 300000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of ₹20,000 to ₹30,000 credited to student bank account",
    ],
    requiredDocuments: [
      "Class 12 / Graduation marksheet",
      "Current year admission fee receipt",
      "Income certificate issued by competent authority",
      "Aadhaar card copy & Bank passbook",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-09-30T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Apply on Vidyasaarathi",
        description: "Submit online application under NSDL Shiksha Sahayog scheme.",
      },
      {
        stepNumber: 2,
        title: "Verification & Merit Ranking",
        description: "Evaluation of academic performance and financial hardship.",
      },
      {
        stepNumber: 3,
        title: "Disbursement",
        description: "Direct bank transfer to selected scholars.",
      },
    ],
    applicationUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceUrl: "https://www.vidyasaarathi.co.in",
    sourceUrl: "https://www.vidyasaarathi.co.in/Vidyasaarathi/scholarship",
    officialSourceName: "Vidyasaarathi Portal / NSDL",
    sourcePortal: "Vidyasaarathi",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Problem Solving", "Computing", "Applied Sciences"],
    careerPaths: ["Software Engineer", "Financial Analyst", "Data Analyst"],
    isActive: true,
  },

  // ==========================================
  // 3. GOVERNMENT PORTAL SCHOLARSHIPS (NSP, AICTE, SSP)
  // ==========================================
  {
    title: "AICTE Pragati Scholarship for Girls in Technical Education",
    provider: "AICTE / Ministry of Education, Govt. of India",
    description:
      "A Government of India scheme implemented by the All India Council for Technical Education (AICTE) on National Scholarship Portal (NSP) to empower young women pursuing technical education in AICTE-approved institutions.",
    awardAmount: "₹50,000 / year",
    awardAmountValue: 50000,
    currency: "INR",
    category: "Government",
    type: "Women",
    eligibilitySummary: "Female students admitted to 1st year of Degree technical course or 2nd year through Lateral Entry in AICTE-approved colleges with annual family income <= ₹8 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Diploma"],
    minimumPercentage: 60,
    minimumCGPA: 6.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "B.Arch", "B.Pharmacy"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Electrical", "Mechanical", "Civil"],
    eligibleYears: ["1st Year", "2nd Year"],
    eligibleLocations: ["India", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹8,00,000",
    maxAnnualIncome: 800000,
    genderRequirement: "Female",
    benefits: [
      "₹50,000 per annum for every year of study towards college tuition, computer, books, and equipment",
      "Direct Benefit Transfer (DBT) into student's Aadhaar-seeded bank account via PFMS",
    ],
    requiredDocuments: [
      "Class 10 and 12 mark sheets",
      "Centralized Admission Process (CAP) / State authority admission letter",
      "Tuition fee receipt",
      "Income Certificate issued by competent Revenue Authority (Tahsildar/DM)",
      "Aadhaar Card linked with Bank Account",
      "Bonafide certificate from college principal",
    ],
    applicationOpenDate: new Date("2026-07-15"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "NSP Portal Registration (OTR)",
        description: "Register with Aadhaar on scholarships.gov.in using One-Time Registration.",
      },
      {
        stepNumber: 2,
        title: "Scheme Selection & Document Upload",
        description: "Select AICTE Pragati Scheme and upload fee receipts, income certificate, and marks cards.",
      },
      {
        stepNumber: 3,
        title: "Institute Level Verification",
        description: "Nodal officer of AICTE-approved college verifies student credentials.",
      },
      {
        stepNumber: 4,
        title: "PFMS DBT Disbursement",
        description: "AICTE sanctions funds directly via DBT.",
      },
    ],
    applicationUrl: "https://scholarships.gov.in",
    officialSourceUrl: "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
    sourceUrl: "https://scholarships.gov.in",
    officialSourceName: "National Scholarship Portal (NSP) / AICTE",
    sourcePortal: "Government",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computing", "Applied Sciences", "Technical Innovation"],
    careerPaths: ["Software Engineer", "Cloud Engineer", "Hardware Engineer", "Cybersecurity Specialist"],
    isActive: true,
  },
  {
    title: "AICTE Saksham Scholarship for Specially-Abled Students",
    provider: "AICTE / Ministry of Education, Govt. of India",
    description:
      "An official Government of India scholarship scheme implemented by AICTE on NSP aimed at encouraging specially-abled students with disability >= 40% to pursue technical degree and diploma education.",
    awardAmount: "₹50,000 / year",
    awardAmountValue: 50000,
    currency: "INR",
    category: "Government",
    type: "Disability",
    eligibilitySummary: "Specially-abled students having disability not less than 40% admitted to 1st year Degree/Diploma technical courses in AICTE-approved institutions with family income <= ₹8.0 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Diploma"],
    minimumPercentage: 50,
    minimumCGPA: 5.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "Diploma"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Electrical", "Mechanical", "Civil", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year"],
    eligibleLocations: ["India", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹8,00,000",
    maxAnnualIncome: 800000,
    genderRequirement: "All",
    benefits: [
      "₹50,000 per annum towards tuition fees, specialized assistive software, devices, and books",
      "Direct Benefit Transfer into Aadhaar-seeded bank account",
    ],
    requiredDocuments: [
      "Unique Disability ID (UDID) card or Disability Certificate issued by authorized Medical Board (min 40% disability)",
      "Class 10 and 12 marksheets",
      "Admission letter in AICTE-approved college & fee receipt",
      "Income certificate from competent revenue authority",
      "Aadhaar card & Bank details",
    ],
    applicationOpenDate: new Date("2026-07-15"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Registration on National Scholarship Portal",
        description: "Register on scholarships.gov.in and fill applicant details.",
      },
      {
        stepNumber: 2,
        title: "Upload Disability Certificate & Documents",
        description: "Upload UDID certificate, college admission receipt, and income proof.",
      },
      {
        stepNumber: 3,
        title: "Institute Level Verification",
        description: "College nodal officer verifies disability and academic documents.",
      },
      {
        stepNumber: 4,
        title: "DBT Payment Release",
        description: "Direct scholarship disbursement via PFMS DBT.",
      },
    ],
    applicationUrl: "https://scholarships.gov.in",
    officialSourceUrl: "https://www.aicte-india.org/schemes/students-development-schemes/Saksham",
    sourceUrl: "https://scholarships.gov.in",
    officialSourceName: "National Scholarship Portal (NSP) / AICTE",
    sourcePortal: "Government",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computing", "Applied Sciences"],
    careerPaths: ["Software Engineer", "Data Analyst", "Accessibility Specialist", "Cloud Developer"],
    isActive: true,
  },
  {
    title: "NSP Central Sector Scheme of Scholarship for College and University Students (PM-USP)",
    provider: "Department of Higher Education, Ministry of Education",
    description:
      "A premier national scholarship scheme by the Government of India on NSP to provide financial assistance to meritorious students from low-income families for pursuing regular undergraduate and postgraduate studies.",
    awardAmount: "₹12,000 – ₹20,000 / year",
    awardAmountValue: 20000,
    currency: "INR",
    category: "Government",
    type: "Merit-cum-Means",
    eligibilitySummary: "Students who scored above 80th percentile in Class 12 board exams pursuing regular degree courses in recognized colleges with family income <= ₹4.5 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate"],
    minimumPercentage: 80,
    minimumCGPA: 7.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "BCA", "MCA", "B.Sc", "M.Tech", "Undergraduate", "Postgraduate"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["India", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹4,50,000",
    maxAnnualIncome: 450000,
    genderRequirement: "All",
    benefits: [
      "₹12,000 per annum for undergraduate degree (1st-3rd year) and ₹20,000 per annum for 4th/5th year professional degree & PG",
      "Direct Benefit Transfer directly to student's bank account",
    ],
    requiredDocuments: [
      "Class 12 board marks card (above 80th percentile)",
      "College admission letter & bonafide certificate",
      "Income certificate issued by competent authority",
      "Aadhaar card copy linked to bank account",
      "Bank passbook",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-10-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "NSP Portal Registration",
        description: "Register with Aadhaar on scholarships.gov.in.",
      },
      {
        stepNumber: 2,
        title: "Scheme Application",
        description: "Choose Central Sector Scheme and submit academic credentials.",
      },
      {
        stepNumber: 3,
        title: "Institute Level & State Nodal Verification",
        description: "College and state nodal officers verify percentile eligibility.",
      },
      {
        stepNumber: 4,
        title: "DBT Disbursement",
        description: "Annual grant credited via PFMS.",
      },
    ],
    applicationUrl: "https://scholarships.gov.in",
    officialSourceUrl: "https://scholarships.gov.in",
    sourceUrl: "https://scholarships.gov.in",
    officialSourceName: "National Scholarship Portal (NSP) / Ministry of Education",
    sourcePortal: "Government",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Problem Solving", "Academic Excellence", "Engineering", "Computing"],
    careerPaths: ["Software Engineer", "Data Scientist", "Core Engineering", "Research Scholar"],
    isActive: true,
  },
  {
    title: "Karnataka State Scholarship Portal (SSP) Post-Matric Scholarship",
    provider: "Government of Karnataka / Social Welfare Department",
    description:
      "Comprehensive unified state scholarship portal by the Government of Karnataka providing full tuition fee reimbursement and maintenance allowance to eligible post-matric, engineering, and postgraduate students in Karnataka.",
    awardAmount: "₹25,000 – ₹1,00,000 / year (Full Tuition + Hosteller Allowance)",
    awardAmountValue: 60000,
    currency: "INR",
    category: "Government",
    type: "Need-based",
    eligibilitySummary: "Domicile students of Karnataka pursuing B.Tech, BCA, MCA, B.Sc, M.Tech, Diploma, or PhD in recognized colleges in Karnataka with valid Kutumba / Caste & Income certificate.",
    eligibleEducationLevel: ["10th", "12th", "Diploma", "Undergraduate", "Postgraduate", "PhD"],
    minimumPercentage: 50,
    minimumCGPA: 5.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "BCA", "MCA", "M.Tech", "B.Sc", "Diploma", "PhD"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "All Branches"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year", "4th Year", "All Years"],
    eligibleLocations: ["Karnataka", "India"],
    eligibleStates: ["Karnataka"],
    incomeRequirement: "Family income <= ₹2,50,000 to ₹8,00,000 depending on category",
    maxAnnualIncome: 800000,
    genderRequirement: "All",
    benefits: [
      "100% tuition and examination fee reimbursement credited to college",
      "Monthly maintenance allowance (Day Scholar / Hosteller) paid directly to student via Aadhaar DBT",
    ],
    requiredDocuments: [
      "Karnataka Kutumba ID / Ration Card",
      "Caste and Income Certificate (RD Number / Nadakacheri issued)",
      "SSLC and PUC / 12th Registration Number & Marks Cards",
      "College Student ID and Admission Fee Receipt",
      "Aadhaar seeded bank account passbook",
      "Hostel stay certificate (if applicable)",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-10-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "SSP Account & Kutumba Authentication",
        description: "Log in with Aadhaar and verify family members using Karnataka Kutumba ID.",
      },
      {
        stepNumber: 2,
        title: "Course & College Details Fetch",
        description: "Select university and college name to automatically pull fee structures and attendance.",
      },
      {
        stepNumber: 3,
        title: "E-Attestation of Documents",
        description: "Submit academic certificates to the designated college E-Attestation officer.",
      },
      {
        stepNumber: 4,
        title: "Department Approval & DBT",
        description: "Social Welfare / Backward Classes department sanctions fee reimbursement via DBT.",
      },
    ],
    applicationUrl: "https://ssp.postmatric.karnataka.gov.in",
    officialSourceUrl: "https://ssp.postmatric.karnataka.gov.in",
    sourceUrl: "https://ssp.postmatric.karnataka.gov.in",
    officialSourceName: "Government of Karnataka State Scholarship Portal",
    sourcePortal: "Government",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computer Science", "Technology", "Applied Sciences"],
    careerPaths: ["Software Engineer", "Full Stack Developer", "System Administrator", "Data Analyst"],
    isActive: true,
  },

  // ==========================================
  // 4. OFFICIAL PROVIDERS & FOUNDATIONS
  // ==========================================
  {
    title: "Reliance Foundation Undergraduate Scholarship",
    provider: "Reliance Foundation",
    description:
      "One of India's largest private scholarship initiatives supporting undergraduate students in all branches of study. The scholarship aims to empower students to build successful careers and contribute to India's socioeconomic growth.",
    awardAmount: "₹2,00,000 (over duration of degree)",
    awardAmountValue: 200000,
    currency: "INR",
    category: "Corporate",
    type: "Merit-cum-Means",
    eligibilitySummary: "Undergraduate degree students across all streams with min. 60% in Class 12 and annual household income under ₹15 Lakhs (preference under ₹2.5 Lakhs).",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "BCA", "B.Sc", "B.Com", "B.A.", "Undergraduate"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "All Branches"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["India", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family household income < ₹15,00,000",
    maxAnnualIncome: 1500000,
    genderRequirement: "All",
    benefits: [
      "Grant of up to ₹2,00,000 over the entire duration of degree program",
      "Opportunity to become part of the vibrant Reliance Foundation Scholar Alumni network",
      "Access to mentorship, leadership workshops, and career development opportunities",
    ],
    requiredDocuments: [
      "Class 10 & 12 Board marksheets",
      "Bonafide Student Certificate / College Admission Proof",
      "Family Income Proof (ITR / Income Certificate / Salary Slip)",
      "Government Identity Proof (Aadhaar Card)",
      "Bank Account Details (Passbook or cancelled cheque)",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-08-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "October 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Online Eligibility Quiz",
        description: "Complete a brief 5-minute online questionnaire on the Reliance Foundation scholarship portal.",
      },
      {
        stepNumber: 2,
        title: "Application Submission",
        description: "Fill out the comprehensive application form with academic details and upload required documents.",
      },
      {
        stepNumber: 3,
        title: "Aptitude Assessment",
        description: "Appear for the mandatory online aptitude test covering verbal, analytical, and numerical ability.",
      },
      {
        stepNumber: 4,
        title: "Selection & Award",
        description: "Announcement of 5,000 selected scholars based on merit-cum-means evaluation.",
      },
    ],
    applicationUrl: "https://www.scholarships.reliancefoundation.org/UG_Scholarship.aspx",
    officialSourceUrl: "https://www.scholarships.reliancefoundation.org",
    sourceUrl: "https://www.scholarships.reliancefoundation.org/UG_Scholarship.aspx",
    officialSourceName: "Reliance Foundation Official Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Problem Solving", "Academic Excellence", "Leadership", "Technology"],
    careerPaths: ["Software Engineer", "Full Stack Developer", "Data Scientist", "Core Engineering", "Finance & Tech"],
    isActive: true,
  },
  {
    title: "Amazon Future Engineer Scholarship Program",
    provider: "Amazon India & Foundation for Academic Excellence",
    description:
      "A comprehensive scholarship program by Amazon dedicated to supporting aspiring female engineering students from low-income backgrounds pursuing Computer Science and allied engineering degrees.",
    awardAmount: "₹50,000 / year + Free Laptop + Mentorship",
    awardAmountValue: 75000,
    currency: "INR",
    category: "STEM/Engineering",
    type: "Women",
    eligibilitySummary: "Female students admitted to 1st year B.Tech/B.E in Computer Science / Information Technology related branches through centralized entrance exams with family income <= ₹3 Lakhs.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 70,
    minimumCGPA: 7.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "B.Tech", "B.E.", "Undergraduate"],
    eligibleBranches: ["Computer Science", "Information Technology", "Artificial Intelligence", "Data Science", "Electronics & Communication"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹3,00,000",
    maxAnnualIncome: 300000,
    genderRequirement: "Female",
    benefits: [
      "₹50,000 per year towards college tuition and educational expenses",
      "Brand-new developer-grade laptop provided free of cost",
      "1-on-1 mentorship by Amazon software engineers",
      "Eligibility for paid Amazon software development internship in 3rd year",
    ],
    requiredDocuments: [
      "Class 10 and Class 12 marks cards",
      "State / JEE Entrance Exam Rank Card",
      "College Admission Slip and Fee Receipt",
      "Government Income Certificate (Tahsildar issued)",
      "Identity Proof (Aadhaar Card)",
    ],
    applicationOpenDate: new Date("2026-07-25"),
    applicationDeadline: new Date("2026-08-17T23:59:59.000Z"), // Closing Soon
    deadlineUnknown: false,
    resultDate: "September 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Application Registration",
        description: "Register on Amazon Future Engineer scholarship portal.",
      },
      {
        stepNumber: 2,
        title: "Academic & Document Verification",
        description: "Submit academic transcripts, income verification, and government entrance rank.",
      },
      {
        stepNumber: 3,
        title: "Telephonic & Virtual Interview",
        description: "Interactive session to verify aspiration, financial background, and academic dedication.",
      },
      {
        stepNumber: 4,
        title: "Induction & Laptop Handover",
        description: "Official welcome event with Amazon leadership and distribution of scholarship grants.",
      },
    ],
    applicationUrl: "https://www.amazonfutureengineer.in",
    officialSourceUrl: "https://www.amazonfutureengineer.in",
    sourceUrl: "https://www.amazonfutureengineer.in",
    officialSourceName: "Amazon Future Engineer Official Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Python", "Java", "Web Development", "Algorithms", "Data Structures"],
    careerPaths: ["Software Development Engineer", "Cloud Architect", "Frontend Developer", "Full Stack Developer"],
    isActive: true,
  },
  {
    title: "Google Generation Scholarship (APAC) – Women in Computer Science",
    provider: "Google",
    description:
      "The Generation Google Scholarship for Asia Pacific helps aspiring women computer scientists excel in computing and technology, become active leaders, and break barriers in technical fields.",
    awardAmount: "USD $2,500 (approx. ₹2,10,000)",
    awardAmountValue: 210000,
    currency: "USD",
    category: "STEM/Engineering",
    type: "Merit-Based",
    eligibilitySummary: "Full-time female undergraduate students studying Computer Science, Computer Engineering, or closely related technical field with strong academic performance.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 75,
    minimumCGPA: 8.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "B.Tech", "B.E.", "BCA", "B.Sc", "Undergraduate"],
    eligibleBranches: ["Computer Science", "Information Technology", "Artificial Intelligence", "Data Science", "Software Engineering"],
    eligibleYears: ["1st Year", "2nd Year", "3rd Year"],
    eligibleLocations: ["India", "International", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "",
    maxAnnualIncome: 0,
    genderRequirement: "Female",
    benefits: [
      "Direct financial grant of $2,500 USD for tuition, books, and study supplies",
      "Invitation to exclusive Google networking sessions, workshops, and mentorship circles",
      "Direct connection with Google engineers and women in tech leadership",
    ],
    requiredDocuments: [
      "Official university academic transcript or marks cards",
      "Updated technical resume highlighting projects, open source, and hackathons",
      "Two short essay responses reflecting passion for technology and diversity advocacy",
      "Google Online Challenge / Coding Assessment completion",
    ],
    applicationOpenDate: new Date("2026-08-01"),
    applicationDeadline: new Date("2026-09-15T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Online Application & Essays",
        description: "Submit resume, transcripts, and answer two short essay prompts on computing impact.",
      },
      {
        stepNumber: 2,
        title: "Google Online Coding Challenge",
        description: "Complete a 60-minute algorithmic and data structures problem solving assessment.",
      },
      {
        stepNumber: 3,
        title: "Committee Evaluation",
        description: "Google panel evaluates essay quality, leadership potential, and technical excellence.",
      },
      {
        stepNumber: 4,
        title: "Recipient Announcement",
        description: "Selected scholars announced and onboarded to Google's Global Scholar Community.",
      },
    ],
    applicationUrl: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",
    officialSourceUrl: "https://buildyourfuture.withgoogle.com",
    sourceUrl: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",
    officialSourceName: "Google Build Your Future Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Data Structures", "Algorithms", "Python", "Java", "C++", "System Design"],
    careerPaths: ["Software Engineer", "AI/ML Engineer", "Backend Developer", "Algorithm Engineer"],
    isActive: true,
  },
  {
    title: "Adobe Research Women-in-Technology Scholarship",
    provider: "Adobe Research",
    description:
      "An elite global scholarship recognizing outstanding female undergraduate and masters students worldwide who demonstrate exceptional academic achievement, innovative computing projects, and leadership in technology.",
    awardAmount: "USD $10,000 (approx. ₹8,30,000) + Adobe Mentorship",
    awardAmountValue: 830000,
    currency: "USD",
    category: "Research",
    type: "Women",
    eligibilitySummary: "Female undergraduate or master's students majoring in Computer Science, Computer Engineering, or related technical disciplines with outstanding academic and research record.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate"],
    minimumPercentage: 80,
    minimumCGPA: 8.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "B.Tech", "B.E.", "M.Tech", "MS", "Undergraduate", "Postgraduate"],
    eligibleBranches: ["Computer Science", "Information Technology", "Artificial Intelligence", "Data Science", "Computer Vision"],
    eligibleYears: ["2nd Year", "3rd Year", "4th Year"],
    eligibleLocations: ["India", "International", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "",
    maxAnnualIncome: 0,
    genderRequirement: "Female",
    benefits: [
      "$10,000 USD one-time financial award",
      "Creative Cloud 12-month subscription",
      "Opportunity for Adobe Research internship interview in India / USA labs",
      "Mentorship from a senior Adobe Research scientist",
    ],
    requiredDocuments: [
      "Curriculum Vitae / Resume detailing technical projects, publications, and open source",
      "Official academic transcripts from all completed semesters",
      "Four essay prompts detailing technical vision, research contributions, and leadership",
      "Up to three letters of recommendation from professors or research advisors",
    ],
    applicationOpenDate: new Date("2026-08-01"),
    applicationDeadline: new Date("2026-09-30T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "December 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Technical Application & Portfolio",
        description: "Submit CV, transcripts, GitHub/portfolio links, and research statements.",
      },
      {
        stepNumber: 2,
        title: "Recommendation Submission",
        description: "Referees receive automated links to submit confidential recommendation letters.",
      },
      {
        stepNumber: 3,
        title: "Adobe Research Committee Review",
        description: "Senior research scientists evaluate innovation, technical rigor, and future potential.",
      },
      {
        stepNumber: 4,
        title: "Winner Selection & Induction",
        description: "Winners announced globally and paired with dedicated Adobe Research mentors.",
      },
    ],
    applicationUrl: "https://research.adobe.com/scholarship/women-in-technology-scholarship",
    officialSourceUrl: "https://research.adobe.com",
    sourceUrl: "https://research.adobe.com/scholarship/women-in-technology-scholarship",
    officialSourceName: "Adobe Research Official Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Machine Learning", "Computer Vision", "Algorithms", "Natural Language Processing", "C++", "Python"],
    careerPaths: ["AI/ML Engineer", "Research Scientist", "Data Scientist", "Computer Vision Engineer"],
    isActive: true,
  },
  {
    title: "Foundation for Excellence (FFE) Engineering Scholarship",
    provider: "Foundation for Excellence (FFE)",
    description:
      "A prestigious national scholarship supporting financially constrained, exceptionally gifted students pursuing 1st year B.E./B.Tech or 5-year Integrated M.Tech programs in India.",
    awardAmount: "₹50,000 / year + Upskilling & Laptops",
    awardAmountValue: 50000,
    currency: "INR",
    category: "Corporate",
    type: "Merit-cum-Means",
    eligibilitySummary: "1st year B.Tech/B.E. or Integrated M.Tech students with min. 70% in Class 12, high state/national entrance rank, and annual family income <= ₹3.0 Lakhs.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate"],
    minimumPercentage: 70,
    minimumCGPA: 7.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "Integrated M.Tech"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Electrical", "Mechanical", "Civil"],
    eligibleYears: ["1st Year"],
    eligibleLocations: ["India", "Karnataka", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹3,00,000",
    maxAnnualIncome: 300000,
    genderRequirement: "All",
    benefits: [
      "Annual scholarship grant of ₹50,000 till course completion",
      "Soft-skills training, technical upskilling, and mentorship from corporate leaders",
    ],
    requiredDocuments: [
      "Class 10 and Class 12 marks cards",
      "JEE Mains / State Entrance Exam rank card",
      "College admission letter & tuition fee receipt",
      "Salary certificate / Revenue Income certificate",
      "Aadhaar card & Student bank account details",
    ],
    applicationOpenDate: new Date("2026-07-01"),
    applicationDeadline: new Date("2026-12-31T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "February 2027",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Online Registration",
        description: "Submit preliminary eligibility form on ffe.org.",
      },
      {
        stepNumber: 2,
        title: "Facilitator Home Verification",
        description: "A volunteer FFE facilitator visits or virtually confirms family background.",
      },
      {
        stepNumber: 3,
        title: "Scholarship Sanction",
        description: "Sanction letter released and annual fee disbursed.",
      },
    ],
    applicationUrl: "https://ffe.org/scholarships/",
    officialSourceUrl: "https://ffe.org",
    sourceUrl: "https://ffe.org/scholarships/",
    officialSourceName: "Foundation for Excellence (FFE)",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Algorithms", "Programming", "Applied Sciences"],
    careerPaths: ["Software Engineer", "Systems Engineer", "Core Engineering", "Data Analyst"],
    isActive: true,
  },
  {
    title: "ONGC Foundation Scholarship for Meritorious SC/ST/OBC/EWS Students",
    provider: "ONGC Foundation / Oil and Natural Gas Corporation",
    description:
      "ONGC Foundation awards 2,000 scholarships annually to meritorious students belonging to economically weaker and marginalized categories pursuing full-time Engineering, MBBS, MBA, and Geology degrees.",
    awardAmount: "₹48,000 / year",
    awardAmountValue: 48000,
    currency: "INR",
    category: "Corporate",
    type: "Minority/category-based",
    eligibilitySummary: "1st year full-time Engineering students with min. 60% in Class 12 or min. 6.0 CGPA and family income <= ₹2.0 Lakhs per annum.",
    eligibleEducationLevel: ["Undergraduate"],
    minimumPercentage: 60,
    minimumCGPA: 6.0,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "Civil", "B.Tech", "B.E.", "Undergraduate"],
    eligibleBranches: ["All Engineering", "Computer Science", "Information Technology", "Electronics", "Electrical", "Mechanical", "Civil", "Petroleum"],
    eligibleYears: ["1st Year", "2nd Year"],
    eligibleLocations: ["India", "All States"],
    eligibleStates: ["All States"],
    incomeRequirement: "Annual family income <= ₹2,00,000",
    maxAnnualIncome: 200000,
    genderRequirement: "All",
    benefits: [
      "Annual assistance of ₹48,000 (₹4,000 per month) for the complete 4-year degree course",
      "50% quota reserved for female candidates across all zones",
    ],
    requiredDocuments: [
      "Class 10 and 12 mark sheets",
      "Caste / Category certificate (SC/ST/OBC/General-EWS)",
      "Income certificate in Hindi/English from competent revenue authority",
      "Proof of admission / Bonafide certificate from college dean/principal",
      "Copy of ECS mandate form certified by bank manager",
    ],
    applicationOpenDate: new Date("2026-07-10"),
    applicationDeadline: new Date("2026-09-20T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "November 2026",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Zone Selection & Online Form",
        description: "Choose relevant geographical zone on the ONGC Scholarship portal and fill personal details.",
      },
      {
        stepNumber: 2,
        title: "Document Upload & Submission",
        description: "Upload academic credentials, certified college bonafide, and ECS mandate.",
      },
      {
        stepNumber: 3,
        title: "Zonal Merit List Generation",
        description: "Merit lists generated zone-wise based on Class 12 marks and economic criteria.",
      },
      {
        stepNumber: 4,
        title: "Annual Scholarship Release",
        description: "Direct transfer of ₹48,000 to bank account with yearly renewal based on academic progression.",
      },
    ],
    applicationUrl: "https://www.ongcscholar.org",
    officialSourceUrl: "https://www.ongcscholar.org",
    sourceUrl: "https://www.ongcscholar.org",
    officialSourceName: "ONGC Foundation Official Scholarship Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Engineering", "Computing", "Applied Physics", "Mathematics"],
    careerPaths: ["Software Engineer", "Cloud Engineer", "Core Engineering", "DevOps Engineer"],
    isActive: true,
  },
  {
    title: "DAAD WISE (Working Internships in Science and Engineering) Fellowship",
    provider: "DAAD (German Academic Exchange Service)",
    description:
      "Prestigious international research scholarship targeting Indian undergraduate students from top Indian engineering institutes (IITs, NITs, BITS, and recognized universities) to do a research internship at German universities and research labs.",
    awardAmount: "€992 / month (approx. ₹90,000/mo) + Travel & Health Insurance",
    awardAmountValue: 270000,
    currency: "EUR",
    category: "International",
    type: "Research",
    eligibilitySummary: "Indian undergraduate students in 5th or 6th semester of B.Tech/B.E with minimum 8.5 CGPA and an invitation/acceptance letter from a German university professor.",
    eligibleEducationLevel: ["Undergraduate", "Postgraduate"],
    minimumPercentage: 80,
    minimumCGPA: 8.5,
    eligibleCourses: ["Engineering", "Computer Science", "Information Technology", "Electronics", "Mechanical", "B.Tech", "B.E.", "Integrated M.Tech", "Undergraduate"],
    eligibleBranches: ["Computer Science", "Information Technology", "Artificial Intelligence", "Electrical", "Mechanical", "All Engineering"],
    eligibleYears: ["3rd Year"],
    eligibleLocations: ["International", "Germany", "India"],
    eligibleStates: ["All States"],
    incomeRequirement: "",
    maxAnnualIncome: 0,
    genderRequirement: "All",
    benefits: [
      "Monthly scholarship grant of €992 for 2 to 3 months research duration",
      "Lump-sum travel subsidy of €1,075 towards international flights",
      "Comprehensive health, accident, and personal liability insurance covered",
      "Direct research experience at premier German research institutions like Max Planck, Fraunhofer, and TU9",
    ],
    requiredDocuments: [
      "Detailed CV in Europass format",
      "Invitation letter from German host professor / institute",
      "Comprehensive Research Project Proposal (2-3 pages)",
      "Official university transcripts with CGPA grading scale",
      "No Objection Certificate (NOC) and reference letter from Indian home university",
    ],
    applicationOpenDate: new Date("2026-08-01"),
    applicationDeadline: new Date("2026-11-01T23:59:59.000Z"),
    deadlineUnknown: false,
    resultDate: "February 2027",
    applicationProcess: [
      {
        stepNumber: 1,
        title: "Secure German Professor Acceptance",
        description: "Contact German university professors in your research domain and secure an internship invitation.",
      },
      {
        stepNumber: 2,
        title: "DAAD Portal Application",
        description: "Register on the DAAD portal and submit research proposal, invitation letter, and transcripts.",
      },
      {
        stepNumber: 3,
        title: "Academic Selection Committee Review",
        description: "DAAD expert committee reviews research viability and academic distinction.",
      },
      {
        stepNumber: 4,
        title: "Visa Assistance & Fellowship Award",
        description: "Official fellowship certificate issued with German student visa facilitation.",
      },
    ],
    applicationUrl: "https://www.daad.in/en/find-funding/scholarship-database/?type=1&detail_to_show=50015295",
    officialSourceUrl: "https://www.daad.in",
    sourceUrl: "https://www.daad.in/en/find-funding/scholarship-database/?type=1&detail_to_show=50015295",
    officialSourceName: "DAAD Official India Portal",
    sourcePortal: "Official Provider",
    isVerified: true,
    isOfficialVerified: true,
    lastVerifiedAt: new Date("2026-08-11"),
    skills: ["Research Methodology", "Machine Learning", "Algorithms", "Advanced Systems", "Scientific Writing"],
    careerPaths: ["Research Scientist", "AI/ML Engineer", "PhD Candidate", "Algorithm Engineer"],
    isActive: true,
  },
];

/**
 * Deduplicate items based on normalized title + provider + URL
 */
const deduplicateScholarships = (list) => {
  const seen = new Set();
  return list.filter((sch) => {
    const key = `${sch.title.toLowerCase().trim()}|${sch.provider.toLowerCase().trim()}|${sch.applicationUrl.toLowerCase().trim()}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
};

const seedScholarships = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI || "mongodb://localhost:27017/career_platform";
    console.log("Connecting to MongoDB for scholarships seeding...");
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB ✅");

    const uniqueScholarships = deduplicateScholarships(verifiedScholarships);
    console.log(`Deduplication check: ${uniqueScholarships.length} unique active scholarships.`);

    console.log("Auditing & refreshing scholarships collection (purging closed ones)...");
    await Scholarship.deleteMany({});

    console.log(`Inserting ${uniqueScholarships.length} verified authoritative active scholarships...`);
    const inserted = await Scholarship.insertMany(uniqueScholarships);
    console.log(`Successfully seeded ${inserted.length} active scholarships! 🎓✨`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding scholarships:", error);
    process.exit(1);
  }
};

if (require.main === module) {
  seedScholarships();
}

module.exports = { seedScholarships, verifiedScholarships, deduplicateScholarships };
